=== 403385120/orign/ZY.CameraNative/PylonCamera/pylon/ConfigFileRegistry/BindingRules.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" id="BindingRules" targetNamespace="http://www.baslerweb.com/pylon" xmlns="http://www.baslerweb.com/pylon" xmlns:NS="http://www.baslerweb.com/pylon" elementFormDefault="qualified">
  <!-- A Binding Rules file defines rules used to define what GenICam XML file is 
       to be used for a device described by the values camera model name, vendor name, 
       and serial numberdifferent cameras.
       In a binding rule file, transport layer specific rules are defined describing
       the source of the camera description device. The source is either a local file
       in the file system or a file that can be downloaded from the camera device.
       -->
  
  <!--
       A Binding Rules files always must start with a top-level element 'BindingRules'. 
       The 'type' attributes specifies whether the rules defined in the file are
       standard rules that are shipped with a pylon installation or custom rules 
       provided by the user. Custom rules can either extend the standard rules or 
       override standard rules (see 'priority' attribute below).
  -->
  <xs:element name="BindingRules">
    <xs:complexType>
      <xs:sequence>
        <!-- For each transport layer (e.g. 'Basler1394', 'BaslerGigE') there is a 'TransportLayer' child 
        element containing the binding rules for devices supported by a transport layer -->
        <xs:element name="TransportLayer" type="TransportLayerType" maxOccurs="unbounded" />
      </xs:sequence>
      <!-- The 'type' attribute (standard rules vs. custom rules) -->
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="custom" />
            <xs:enumeration value="standard" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <!-- A 'TransportLayer' element has 'Rule' elements as childs -->
  <xs:complexType name="TransportLayerType">
    <xs:sequence>
      <xs:element name="Rule" type="RuleType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" use="required" />
  </xs:complexType>

  <!-- Syntax of a rule. The rule consists of regular expressions for the camera vendor, 
       camera model name and serial number. These regular expressions are matched against
       the values used for creating a pylon device.
       In addition to the regular expressions, the rule specifies whether the XML file 
       should be downloaded from the camera device or if a file in the local file system
       should be used.
  -->
  <xs:complexType name="RuleType">
    <xs:all>
      <!-- Optional description of the rule -->
      <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>

      <!-- Camera Manufacturer (e.g. 'Basler'). This field is interpreted as a regular 
           expression following the Perl syntax for regular expressions. -->
      <xs:element name="Manufacturer" type="xs:string" default=".*" minOccurs="0" />

      <!-- Camera model name (e.g. sca640.*). This field is interpreted as a regular 
           expression following the Perl syntax for regular expressions. -->
      <xs:element name="Name" type="xs:string" default=".*" minOccurs="0" />
      
      <!-- Serial number of the device. This field is interpreted as a regular 
           expression following the Perl syntax for regular expressions. -->
      <xs:element name="SerialNumber" type="xs:string" default=".*" minOccurs="0" />

      <!-- Specifies if the device factory should try to download the XML file 
           from the device. This field has higher priority than the 'File' field
           (see below). Allowed values are 'yes' and 'no' -->
      <xs:element name="Download">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="yes" />
            <xs:enumeration value="no" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <!-- Location of a local XML file to use. If Download=yes, the file is
           only used when downloading the XML file from the camera fails.
           When Download=no, a file must be specified. 
           The value of the 'File' field can refer to environment variables,
           example: '$(GENICAM_ROOT)/xml/genapi/Basler/BaslerGigE.xml'
       -->
      <xs:element name="File" type="xs:string" default="" minOccurs="0" />
      <!-- Location of a local XML file to merge in the normal XML for the camera. 
        Mainly used by developers. -->
      <xs:element name="AdditionalFile" type="xs:string" default="" minOccurs="0" maxOccurs="1" /> 
    </xs:all>
 
    <!-- Each rule has a priority (the higher the number, the higher the priority).
         When several rules match to a given device, the rule with the highest priority is taken.
         If both a custom rule and a standard rule with the same priority are matching, the 
         custom rule will be applied.
         If there is an ambiguity, e.g., more than one custom rule with 
         the same high priority are matching, the transport layer will throw an exception. 
         -->
    <xs:attribute name="priority" type="xs:unsignedInt" use="required" />
  </xs:complexType>
</xs:schema>

=== 403385120/orign/ZY.CameraNative/PylonCamera/pylon/ConfigFileRegistry/StandardRules.xml
<?xml version="1.0"  encoding="utf-8" ?>

<!--

  (c) 2007 by Basler Vision Technologies
  Section: Basler Components
  Project: PYLON
  Author:  AH

This file specifies the rules defining how to bind GenICam XML 
configuration files to pylon devices.

THESE ARE THE PYLON STANDARD RULES, DON'T MODIFY THESE RULES!

Create a new rules file (a "custom" rules file) to add new custom rules or to override the 
standard rules. Store the custom rules file at the same location as the 
standard rules file.

Example for a custom rules file:

<?xml version="1.0"  encoding="utf-8" ?>
<BindingRules
  type="custom" 
  xmlns="http://www.baslerweb.com/pylon" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.baslerweb.com/pylon BindingRules.xsd" >
  <TransportLayer name="Basler1394">
    <Rule priority="10">
      <Manufacturer>Basler</Manufacturer>
      <Name>sca.*custom</Name>
      <SerialNumber>.*</SerialNumber>
      <Download>no</Download>
      <File>$(GENICAM_XMLPATH)/Basler/Baslerscout1394_custom.xml</File>
    </Rule>
  </TransportLayer>
    <TransportLayer name="BaslerGigE">
      <Rule priority="10">
        <Manufacturer>Basler</Manufacturer>
        <Name>rul.*custom</Name>
        <SerialNumber>.*</SerialNumber>
        <Download>no</Download>
        <File>$(GENICAM_XMLPATH)/Basler/Basler_runner_custom.xml</File>
      </Rule>
  </TransportLayer>
</BindingRules>
  
  The above sample file defines two custom rules. The first one matches Basler 1394 cameras whose model 
  names start with 'sca' and end with 'custom'. The second one matches Basler GigE cameras
  whose model names start with 'rul' and end with 'custom'.
  For the Basler 1394 and GigE cameras the specified XML configuration files are used. 
  For more details about the grammar of rules files see the BindingRules.xsd XML schema file.
-->

<BindingRules
    type="standard"
    xmlns="http://www.baslerweb.com/pylon"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.baslerweb.com/pylon BindingRules.xsd" >

    <!-- Rules for 1394 cameras -->
    <TransportLayer name="Basler1394">
        <!-- For all 1394 cameras always use the XML file installed with pylon -->
        <Rule priority="0">
            <Manufacturer>.*</Manufacturer>
            <Name>.*</Name>
            <SerialNumber>.*</SerialNumber>
            <Download>no</Download>
            <File>$(GENICAM_XMLPATH)/Basler/Basler_scout_1394.xml</File>
        </Rule>
        <Rule priority="1">
            <Manufacturer>.*</Manufacturer>
            <Name>A(1|3|6).*f(c)*</Name>
            <SerialNumber>.*</SerialNumber>
            <Download>no</Download>
            <File>$(GENICAM_XMLPATH)/Basler/Basler_A1_A3_A6_1394.xml</File>
        </Rule>
    </TransportLayer>

    <!-- Rules for GigE Vision cameras -->
    <TransportLayer name="BaslerGigE">
        <!-- Rule for all GigE Vision cameras: Download the configuration file from the device -->
        <Rule priority="0">
            <Manufacturer>.*</Manufacturer>
            <Name>.*</Name>
            <SerialNumber>.*</SerialNumber>
            <Download>yes</Download>
        </Rule>

    </TransportLayer>


    <!-- Rules for Camera Link cameras -->
    <TransportLayer name="BaslerCameraLink">
        <!-- Rule for all Basler CameraLink cameras. Always try to download the configuration file from the device.
         When for some reason the download fails, the configuration file shipped with the 
         pylon installation should be used. -->
        <Rule priority="0">
            <Manufacturer>Basler</Manufacturer>
            <Name>.*</Name>
            <SerialNumber>.*</SerialNumber>
            <Download>yes</Download>
            <File>$(GENICAM_XMLPATH)/Basler/Basler_CameraLink.xml</File>
        </Rule>
        
        <!-- for convenience add some rules for specific families.
             Currently we're using the same XMl file for all CL cameras. -->
        <Rule priority="1">
            <Manufacturer>Basler</Manufacturer>
            <Name>avA.*</Name>
            <SerialNumber>.*</SerialNumber>
            <Download>yes</Download>
            <File>$(GENICAM_XMLPATH)/Basler/Basler_CameraLink.xml</File>
        </Rule>
        <Rule priority="1">
            <Manufacturer>Basler</Manufacturer>
            <Name>scA.*</Name>
            <SerialNumber>.*</SerialNumber>
            <Download>yes</Download>
            <File>$(GENICAM_XMLPATH)/Basler/Basler_CameraLink.xml</File>
        </Rule>
        <Rule priority="1">
            <Manufacturer>Basler</Manufacturer>
            <Name>piA.*</Name>
            <SerialNumber>.*</SerialNumber>
            <Download>yes</Download>
            <File>$(GENICAM_XMLPATH)/Basler/Basler_CameraLink.xml</File>
        </Rule>
    </TransportLayer>

</BindingRules>
